/*
===============================================================================
Stored Procedure: Master ETL Pipeline (Load All Layers)
===============================================================================
Script Purpose:
    This is the "Controller" procedure for the entire Data Warehouse.
    It executes the full ETL pipeline in the correct dependency order:
    Bronze -> Silver -> Gold.

    Features:
    - Centralized execution entry point.
    - Integrated Error Handling across all layers.
    - Identity-based Batch ID generation (Thread-safe).
    - Failure Safeguard: Aborts if metadata configuration is missing.
===============================================================================
*/

CREATE OR ALTER PROCEDURE init.load_all AS
BEGIN
    DECLARE @batch_start_time DATETIME = GETDATE();
    DECLARE @batch_end_time DATETIME;
    DECLARE @batch_id INT; 

    BEGIN TRY
        -- ======================================================
        -- 0. BATCH ID GENERATION (Identity-Safe Logic)
        -- ======================================================
        -- Insert an initial "In Progress" record to reserve the Batch ID
        INSERT INTO audit.etl_log (table_name, start_time, status)
        VALUES ('MASTER_PIPELINE', @batch_start_time, 'In Progress');

        -- Capture the ID generated by the IDENTITY column
        SET @batch_id = SCOPE_IDENTITY();

        PRINT '================================================';
        PRINT 'STARTING MASTER ETL PIPELINE | BATCH ID: ' + CAST(@batch_id AS NVARCHAR);
        PRINT '================================================';
        PRINT '>> Start Time: ' + CAST(@batch_start_time AS NVARCHAR);

        -- ======================================================
        -- 1. METADATA VALIDATION (The "Hard Stop" Check)
        -- ======================================================
        IF NOT EXISTS (SELECT 1 FROM audit.etl_config WHERE is_active = 1)
        BEGIN
            -- Using THROW: Error Number (50000+), Message, State
            THROW 50001, 'CRITICAL ERROR: No active metadata found in audit.etl_config. Pipeline aborted to prevent incomplete data load.', 1;
        END

        -- ======================================================
        -- 2. BRONZE LAYER (Landing Raw Data)
        -- ======================================================
        PRINT '------------------------------------------------';
        PRINT 'STEP 1: LOADING BRONZE LAYER';
        PRINT '------------------------------------------------';
        EXEC bronze.load_bronze @batch_id = @batch_id; 

        -- ======================================================
        -- 3. SILVER LAYER (Cleaning & Standardizing)
        -- ======================================================
        PRINT '------------------------------------------------';
        PRINT 'STEP 2: LOADING SILVER LAYER';
        PRINT '------------------------------------------------';
        EXEC silver.load_silver @batch_id = @batch_id; 

        -- ======================================================
        -- 4. GOLD LAYER (Materializing Star Schema)
        -- ======================================================
        PRINT '------------------------------------------------';
        PRINT 'STEP 3: LOADING GOLD LAYER';
        PRINT '------------------------------------------------';
        EXEC gold.load_gold @batch_id = @batch_id; 

        SET @batch_end_time = GETDATE();

        -- ======================================================
        -- FINAL AUDIT UPDATE (Success)
        -- ======================================================
        UPDATE audit.etl_log
        SET end_time = @batch_end_time,
            status = 'Success'
        WHERE log_id = @batch_id; -- log_id is the primary key and our batch_id

        PRINT '================================================';
        PRINT 'MASTER ETL PIPELINE COMPLETED SUCCESSFULLY';
        PRINT ' - Total Duration: ' + CAST(DATEDIFF(SECOND, @batch_start_time, @batch_end_time) AS NVARCHAR) + ' seconds';
        PRINT '================================================';

    END TRY
    BEGIN CATCH
        -- Ensure end_time is captured even on failure
        SET @batch_end_time = GETDATE();

        PRINT '================================================';
        PRINT 'MASTER PIPELINE FAILED!';
        PRINT 'Error Message: ' + ERROR_MESSAGE();
        PRINT '================================================';

        -- Update the existing log record with failure details
        -- If @batch_id is NULL (failure during generation), this will simply do nothing
        IF @batch_id IS NOT NULL
        BEGIN
            UPDATE audit.etl_log
            SET end_time = @batch_end_time,
                status = 'Failed',
                error_message = ERROR_MESSAGE()
            WHERE log_id = @batch_id;
        END

        -- Optional: Re-throw if you want the calling application to see the error
        -- THROW; 
    END CATCH
END
GO
